//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace phians.get_interface {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="get_interface.phians_webservice_N1Soap")]
    public interface phians_webservice_N1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 clientele 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_info", ReplyAction="*")]
        phians.get_interface.get_infoResponse get_info(phians.get_interface.get_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_info", ReplyAction="*")]
        System.Threading.Tasks.Task<phians.get_interface.get_infoResponse> get_infoAsync(phians.get_interface.get_infoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 JobNum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderNUM", ReplyAction="*")]
        phians.get_interface.GetOrderNUMResponse GetOrderNUM(phians.get_interface.GetOrderNUMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderNUM", ReplyAction="*")]
        System.Threading.Tasks.Task<phians.get_interface.GetOrderNUMResponse> GetOrderNUMAsync(phians.get_interface.GetOrderNUMRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 LZKH 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getmethod", ReplyAction="*")]
        phians.get_interface.GetmethodResponse Getmethod(phians.get_interface.GetmethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getmethod", ReplyAction="*")]
        System.Threading.Tasks.Task<phians.get_interface.GetmethodResponse> GetmethodAsync(phians.get_interface.GetmethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_infoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_info", Namespace="http://tempuri.org/", Order=0)]
        public phians.get_interface.get_infoRequestBody Body;
        
        public get_infoRequest() {
        }
        
        public get_infoRequest(phians.get_interface.get_infoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_infoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientele;
        
        public get_infoRequestBody() {
        }
        
        public get_infoRequestBody(string clientele) {
            this.clientele = clientele;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_infoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_infoResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians.get_interface.get_infoResponseBody Body;
        
        public get_infoResponse() {
        }
        
        public get_infoResponse(phians.get_interface.get_infoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_infoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string get_infoResult;
        
        public get_infoResponseBody() {
        }
        
        public get_infoResponseBody(string get_infoResult) {
            this.get_infoResult = get_infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderNUMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderNUM", Namespace="http://tempuri.org/", Order=0)]
        public phians.get_interface.GetOrderNUMRequestBody Body;
        
        public GetOrderNUMRequest() {
        }
        
        public GetOrderNUMRequest(phians.get_interface.GetOrderNUMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderNUMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JobNum;
        
        public GetOrderNUMRequestBody() {
        }
        
        public GetOrderNUMRequestBody(string JobNum) {
            this.JobNum = JobNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderNUMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderNUMResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians.get_interface.GetOrderNUMResponseBody Body;
        
        public GetOrderNUMResponse() {
        }
        
        public GetOrderNUMResponse(phians.get_interface.GetOrderNUMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderNUMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOrderNUMResult;
        
        public GetOrderNUMResponseBody() {
        }
        
        public GetOrderNUMResponseBody(string GetOrderNUMResult) {
            this.GetOrderNUMResult = GetOrderNUMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetmethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getmethod", Namespace="http://tempuri.org/", Order=0)]
        public phians.get_interface.GetmethodRequestBody Body;
        
        public GetmethodRequest() {
        }
        
        public GetmethodRequest(phians.get_interface.GetmethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetmethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LZKH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VORNR;
        
        public GetmethodRequestBody() {
        }
        
        public GetmethodRequestBody(string LZKH, string VORNR) {
            this.LZKH = LZKH;
            this.VORNR = VORNR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetmethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetmethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians.get_interface.GetmethodResponseBody Body;
        
        public GetmethodResponse() {
        }
        
        public GetmethodResponse(phians.get_interface.GetmethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetmethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetmethodResult;
        
        public GetmethodResponseBody() {
        }
        
        public GetmethodResponseBody(string GetmethodResult) {
            this.GetmethodResult = GetmethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface phians_webservice_N1SoapChannel : phians.get_interface.phians_webservice_N1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class phians_webservice_N1SoapClient : System.ServiceModel.ClientBase<phians.get_interface.phians_webservice_N1Soap>, phians.get_interface.phians_webservice_N1Soap {
        
        public phians_webservice_N1SoapClient() {
        }
        
        public phians_webservice_N1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public phians_webservice_N1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public phians_webservice_N1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public phians_webservice_N1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians.get_interface.get_infoResponse phians.get_interface.phians_webservice_N1Soap.get_info(phians.get_interface.get_infoRequest request) {
            return base.Channel.get_info(request);
        }
        
        public string get_info(string clientele) {
            phians.get_interface.get_infoRequest inValue = new phians.get_interface.get_infoRequest();
            inValue.Body = new phians.get_interface.get_infoRequestBody();
            inValue.Body.clientele = clientele;
            phians.get_interface.get_infoResponse retVal = ((phians.get_interface.phians_webservice_N1Soap)(this)).get_info(inValue);
            return retVal.Body.get_infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians.get_interface.get_infoResponse> phians.get_interface.phians_webservice_N1Soap.get_infoAsync(phians.get_interface.get_infoRequest request) {
            return base.Channel.get_infoAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians.get_interface.get_infoResponse> get_infoAsync(string clientele) {
            phians.get_interface.get_infoRequest inValue = new phians.get_interface.get_infoRequest();
            inValue.Body = new phians.get_interface.get_infoRequestBody();
            inValue.Body.clientele = clientele;
            return ((phians.get_interface.phians_webservice_N1Soap)(this)).get_infoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians.get_interface.GetOrderNUMResponse phians.get_interface.phians_webservice_N1Soap.GetOrderNUM(phians.get_interface.GetOrderNUMRequest request) {
            return base.Channel.GetOrderNUM(request);
        }
        
        public string GetOrderNUM(string JobNum) {
            phians.get_interface.GetOrderNUMRequest inValue = new phians.get_interface.GetOrderNUMRequest();
            inValue.Body = new phians.get_interface.GetOrderNUMRequestBody();
            inValue.Body.JobNum = JobNum;
            phians.get_interface.GetOrderNUMResponse retVal = ((phians.get_interface.phians_webservice_N1Soap)(this)).GetOrderNUM(inValue);
            return retVal.Body.GetOrderNUMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians.get_interface.GetOrderNUMResponse> phians.get_interface.phians_webservice_N1Soap.GetOrderNUMAsync(phians.get_interface.GetOrderNUMRequest request) {
            return base.Channel.GetOrderNUMAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians.get_interface.GetOrderNUMResponse> GetOrderNUMAsync(string JobNum) {
            phians.get_interface.GetOrderNUMRequest inValue = new phians.get_interface.GetOrderNUMRequest();
            inValue.Body = new phians.get_interface.GetOrderNUMRequestBody();
            inValue.Body.JobNum = JobNum;
            return ((phians.get_interface.phians_webservice_N1Soap)(this)).GetOrderNUMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians.get_interface.GetmethodResponse phians.get_interface.phians_webservice_N1Soap.Getmethod(phians.get_interface.GetmethodRequest request) {
            return base.Channel.Getmethod(request);
        }
        
        public string Getmethod(string LZKH, string VORNR) {
            phians.get_interface.GetmethodRequest inValue = new phians.get_interface.GetmethodRequest();
            inValue.Body = new phians.get_interface.GetmethodRequestBody();
            inValue.Body.LZKH = LZKH;
            inValue.Body.VORNR = VORNR;
            phians.get_interface.GetmethodResponse retVal = ((phians.get_interface.phians_webservice_N1Soap)(this)).Getmethod(inValue);
            return retVal.Body.GetmethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians.get_interface.GetmethodResponse> phians.get_interface.phians_webservice_N1Soap.GetmethodAsync(phians.get_interface.GetmethodRequest request) {
            return base.Channel.GetmethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians.get_interface.GetmethodResponse> GetmethodAsync(string LZKH, string VORNR) {
            phians.get_interface.GetmethodRequest inValue = new phians.get_interface.GetmethodRequest();
            inValue.Body = new phians.get_interface.GetmethodRequestBody();
            inValue.Body.LZKH = LZKH;
            inValue.Body.VORNR = VORNR;
            return ((phians.get_interface.phians_webservice_N1Soap)(this)).GetmethodAsync(inValue);
        }
    }
}
