//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace phians_laboratory.MESINTERFACE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MESINTERFACE.MES_INTERFACESoap")]
    public interface MES_INTERFACESoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 WORKID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MESINFO", ReplyAction="*")]
        phians_laboratory.MESINTERFACE.GET_MESINFOResponse GET_MESINFO(phians_laboratory.MESINTERFACE.GET_MESINFORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MESINFO", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFOResponse> GET_MESINFOAsync(phians_laboratory.MESINTERFACE.GET_MESINFORequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 WORKID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MESINFO2", ReplyAction="*")]
        phians_laboratory.MESINTERFACE.GET_MESINFO2Response GET_MESINFO2(phians_laboratory.MESINTERFACE.GET_MESINFO2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MESINFO2", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFO2Response> GET_MESINFO2Async(phians_laboratory.MESINTERFACE.GET_MESINFO2Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 WORKID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MESINFO1", ReplyAction="*")]
        phians_laboratory.MESINTERFACE.GET_MESINFO1Response GET_MESINFO1(phians_laboratory.MESINTERFACE.GET_MESINFO1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MESINFO1", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFO1Response> GET_MESINFO1Async(phians_laboratory.MESINTERFACE.GET_MESINFO1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_MESINFORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_MESINFO", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.MESINTERFACE.GET_MESINFORequestBody Body;
        
        public GET_MESINFORequest() {
        }
        
        public GET_MESINFORequest(phians_laboratory.MESINTERFACE.GET_MESINFORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_MESINFORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WORKID;
        
        public GET_MESINFORequestBody() {
        }
        
        public GET_MESINFORequestBody(string WORKID) {
            this.WORKID = WORKID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_MESINFOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_MESINFOResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.MESINTERFACE.GET_MESINFOResponseBody Body;
        
        public GET_MESINFOResponse() {
        }
        
        public GET_MESINFOResponse(phians_laboratory.MESINTERFACE.GET_MESINFOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_MESINFOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_MESINFOResult;
        
        public GET_MESINFOResponseBody() {
        }
        
        public GET_MESINFOResponseBody(string GET_MESINFOResult) {
            this.GET_MESINFOResult = GET_MESINFOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_MESINFO2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_MESINFO2", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.MESINTERFACE.GET_MESINFO2RequestBody Body;
        
        public GET_MESINFO2Request() {
        }
        
        public GET_MESINFO2Request(phians_laboratory.MESINTERFACE.GET_MESINFO2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_MESINFO2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WORKID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int page;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pagesize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string order;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sortby;
        
        public GET_MESINFO2RequestBody() {
        }
        
        public GET_MESINFO2RequestBody(string WORKID, int page, int pagesize, string order, string sortby) {
            this.WORKID = WORKID;
            this.page = page;
            this.pagesize = pagesize;
            this.order = order;
            this.sortby = sortby;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_MESINFO2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_MESINFO2Response", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.MESINTERFACE.GET_MESINFO2ResponseBody Body;
        
        public GET_MESINFO2Response() {
        }
        
        public GET_MESINFO2Response(phians_laboratory.MESINTERFACE.GET_MESINFO2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_MESINFO2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_MESINFO2Result;
        
        public GET_MESINFO2ResponseBody() {
        }
        
        public GET_MESINFO2ResponseBody(string GET_MESINFO2Result) {
            this.GET_MESINFO2Result = GET_MESINFO2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_MESINFO1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_MESINFO1", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.MESINTERFACE.GET_MESINFO1RequestBody Body;
        
        public GET_MESINFO1Request() {
        }
        
        public GET_MESINFO1Request(phians_laboratory.MESINTERFACE.GET_MESINFO1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_MESINFO1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WORKID;
        
        public GET_MESINFO1RequestBody() {
        }
        
        public GET_MESINFO1RequestBody(string WORKID) {
            this.WORKID = WORKID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GET_MESINFO1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GET_MESINFO1Response", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.MESINTERFACE.GET_MESINFO1ResponseBody Body;
        
        public GET_MESINFO1Response() {
        }
        
        public GET_MESINFO1Response(phians_laboratory.MESINTERFACE.GET_MESINFO1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GET_MESINFO1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GET_MESINFO1Result;
        
        public GET_MESINFO1ResponseBody() {
        }
        
        public GET_MESINFO1ResponseBody(string GET_MESINFO1Result) {
            this.GET_MESINFO1Result = GET_MESINFO1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MES_INTERFACESoapChannel : phians_laboratory.MESINTERFACE.MES_INTERFACESoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MES_INTERFACESoapClient : System.ServiceModel.ClientBase<phians_laboratory.MESINTERFACE.MES_INTERFACESoap>, phians_laboratory.MESINTERFACE.MES_INTERFACESoap {
        
        public MES_INTERFACESoapClient() {
        }
        
        public MES_INTERFACESoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MES_INTERFACESoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MES_INTERFACESoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MES_INTERFACESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.MESINTERFACE.GET_MESINFOResponse phians_laboratory.MESINTERFACE.MES_INTERFACESoap.GET_MESINFO(phians_laboratory.MESINTERFACE.GET_MESINFORequest request) {
            return base.Channel.GET_MESINFO(request);
        }
        
        public string GET_MESINFO(string WORKID) {
            phians_laboratory.MESINTERFACE.GET_MESINFORequest inValue = new phians_laboratory.MESINTERFACE.GET_MESINFORequest();
            inValue.Body = new phians_laboratory.MESINTERFACE.GET_MESINFORequestBody();
            inValue.Body.WORKID = WORKID;
            phians_laboratory.MESINTERFACE.GET_MESINFOResponse retVal = ((phians_laboratory.MESINTERFACE.MES_INTERFACESoap)(this)).GET_MESINFO(inValue);
            return retVal.Body.GET_MESINFOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFOResponse> phians_laboratory.MESINTERFACE.MES_INTERFACESoap.GET_MESINFOAsync(phians_laboratory.MESINTERFACE.GET_MESINFORequest request) {
            return base.Channel.GET_MESINFOAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFOResponse> GET_MESINFOAsync(string WORKID) {
            phians_laboratory.MESINTERFACE.GET_MESINFORequest inValue = new phians_laboratory.MESINTERFACE.GET_MESINFORequest();
            inValue.Body = new phians_laboratory.MESINTERFACE.GET_MESINFORequestBody();
            inValue.Body.WORKID = WORKID;
            return ((phians_laboratory.MESINTERFACE.MES_INTERFACESoap)(this)).GET_MESINFOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.MESINTERFACE.GET_MESINFO2Response phians_laboratory.MESINTERFACE.MES_INTERFACESoap.GET_MESINFO2(phians_laboratory.MESINTERFACE.GET_MESINFO2Request request) {
            return base.Channel.GET_MESINFO2(request);
        }
        
        public string GET_MESINFO2(string WORKID, int page, int pagesize, string order, string sortby) {
            phians_laboratory.MESINTERFACE.GET_MESINFO2Request inValue = new phians_laboratory.MESINTERFACE.GET_MESINFO2Request();
            inValue.Body = new phians_laboratory.MESINTERFACE.GET_MESINFO2RequestBody();
            inValue.Body.WORKID = WORKID;
            inValue.Body.page = page;
            inValue.Body.pagesize = pagesize;
            inValue.Body.order = order;
            inValue.Body.sortby = sortby;
            phians_laboratory.MESINTERFACE.GET_MESINFO2Response retVal = ((phians_laboratory.MESINTERFACE.MES_INTERFACESoap)(this)).GET_MESINFO2(inValue);
            return retVal.Body.GET_MESINFO2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFO2Response> phians_laboratory.MESINTERFACE.MES_INTERFACESoap.GET_MESINFO2Async(phians_laboratory.MESINTERFACE.GET_MESINFO2Request request) {
            return base.Channel.GET_MESINFO2Async(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFO2Response> GET_MESINFO2Async(string WORKID, int page, int pagesize, string order, string sortby) {
            phians_laboratory.MESINTERFACE.GET_MESINFO2Request inValue = new phians_laboratory.MESINTERFACE.GET_MESINFO2Request();
            inValue.Body = new phians_laboratory.MESINTERFACE.GET_MESINFO2RequestBody();
            inValue.Body.WORKID = WORKID;
            inValue.Body.page = page;
            inValue.Body.pagesize = pagesize;
            inValue.Body.order = order;
            inValue.Body.sortby = sortby;
            return ((phians_laboratory.MESINTERFACE.MES_INTERFACESoap)(this)).GET_MESINFO2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.MESINTERFACE.GET_MESINFO1Response phians_laboratory.MESINTERFACE.MES_INTERFACESoap.GET_MESINFO1(phians_laboratory.MESINTERFACE.GET_MESINFO1Request request) {
            return base.Channel.GET_MESINFO1(request);
        }
        
        public string GET_MESINFO1(string WORKID) {
            phians_laboratory.MESINTERFACE.GET_MESINFO1Request inValue = new phians_laboratory.MESINTERFACE.GET_MESINFO1Request();
            inValue.Body = new phians_laboratory.MESINTERFACE.GET_MESINFO1RequestBody();
            inValue.Body.WORKID = WORKID;
            phians_laboratory.MESINTERFACE.GET_MESINFO1Response retVal = ((phians_laboratory.MESINTERFACE.MES_INTERFACESoap)(this)).GET_MESINFO1(inValue);
            return retVal.Body.GET_MESINFO1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFO1Response> phians_laboratory.MESINTERFACE.MES_INTERFACESoap.GET_MESINFO1Async(phians_laboratory.MESINTERFACE.GET_MESINFO1Request request) {
            return base.Channel.GET_MESINFO1Async(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.MESINTERFACE.GET_MESINFO1Response> GET_MESINFO1Async(string WORKID) {
            phians_laboratory.MESINTERFACE.GET_MESINFO1Request inValue = new phians_laboratory.MESINTERFACE.GET_MESINFO1Request();
            inValue.Body = new phians_laboratory.MESINTERFACE.GET_MESINFO1RequestBody();
            inValue.Body.WORKID = WORKID;
            return ((phians_laboratory.MESINTERFACE.MES_INTERFACESoap)(this)).GET_MESINFO1Async(inValue);
        }
    }
}
