//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace phians_laboratory.get_interface {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="get_interface.phians_webservice_N1Soap")]
    public interface phians_webservice_N1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 clientele 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_info", ReplyAction="*")]
        phians_laboratory.get_interface.get_infoResponse get_info(phians_laboratory.get_interface.get_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_info", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.get_infoResponse> get_infoAsync(phians_laboratory.get_interface.get_infoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 JobNum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderNUM", ReplyAction="*")]
        phians_laboratory.get_interface.GetOrderNUMResponse GetOrderNUM(phians_laboratory.get_interface.GetOrderNUMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderNUM", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.GetOrderNUMResponse> GetOrderNUMAsync(phians_laboratory.get_interface.GetOrderNUMRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 LZKH 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getmethod", ReplyAction="*")]
        phians_laboratory.get_interface.GetmethodResponse Getmethod(phians_laboratory.get_interface.GetmethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getmethod", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.GetmethodResponse> GetmethodAsync(phians_laboratory.get_interface.GetmethodRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Inspection_NO 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhysicsInfo_", ReplyAction="*")]
        phians_laboratory.get_interface.GetPhysicsInfo_Response GetPhysicsInfo_(phians_laboratory.get_interface.GetPhysicsInfo_Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhysicsInfo_", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.GetPhysicsInfo_Response> GetPhysicsInfo_Async(phians_laboratory.get_interface.GetPhysicsInfo_Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dd 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        phians_laboratory.get_interface.testResponse test(phians_laboratory.get_interface.testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.testResponse> testAsync(phians_laboratory.get_interface.testRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fmName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testParameters", ReplyAction="*")]
        phians_laboratory.get_interface.testParametersResponse testParameters(phians_laboratory.get_interface.testParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.testParametersResponse> testParametersAsync(phians_laboratory.get_interface.testParametersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_infoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_info", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.get_infoRequestBody Body;
        
        public get_infoRequest() {
        }
        
        public get_infoRequest(phians_laboratory.get_interface.get_infoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_infoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientele;
        
        public get_infoRequestBody() {
        }
        
        public get_infoRequestBody(string clientele) {
            this.clientele = clientele;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_infoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_infoResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.get_infoResponseBody Body;
        
        public get_infoResponse() {
        }
        
        public get_infoResponse(phians_laboratory.get_interface.get_infoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_infoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string get_infoResult;
        
        public get_infoResponseBody() {
        }
        
        public get_infoResponseBody(string get_infoResult) {
            this.get_infoResult = get_infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderNUMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderNUM", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.GetOrderNUMRequestBody Body;
        
        public GetOrderNUMRequest() {
        }
        
        public GetOrderNUMRequest(phians_laboratory.get_interface.GetOrderNUMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderNUMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JobNum;
        
        public GetOrderNUMRequestBody() {
        }
        
        public GetOrderNUMRequestBody(string JobNum) {
            this.JobNum = JobNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderNUMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderNUMResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.GetOrderNUMResponseBody Body;
        
        public GetOrderNUMResponse() {
        }
        
        public GetOrderNUMResponse(phians_laboratory.get_interface.GetOrderNUMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderNUMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOrderNUMResult;
        
        public GetOrderNUMResponseBody() {
        }
        
        public GetOrderNUMResponseBody(string GetOrderNUMResult) {
            this.GetOrderNUMResult = GetOrderNUMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetmethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getmethod", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.GetmethodRequestBody Body;
        
        public GetmethodRequest() {
        }
        
        public GetmethodRequest(phians_laboratory.get_interface.GetmethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetmethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LZKH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VORNR;
        
        public GetmethodRequestBody() {
        }
        
        public GetmethodRequestBody(string LZKH, string VORNR) {
            this.LZKH = LZKH;
            this.VORNR = VORNR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetmethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetmethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.GetmethodResponseBody Body;
        
        public GetmethodResponse() {
        }
        
        public GetmethodResponse(phians_laboratory.get_interface.GetmethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetmethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetmethodResult;
        
        public GetmethodResponseBody() {
        }
        
        public GetmethodResponseBody(string GetmethodResult) {
            this.GetmethodResult = GetmethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhysicsInfo_Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhysicsInfo_", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.GetPhysicsInfo_RequestBody Body;
        
        public GetPhysicsInfo_Request() {
        }
        
        public GetPhysicsInfo_Request(phians_laboratory.get_interface.GetPhysicsInfo_RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhysicsInfo_RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Inspection_NO;
        
        public GetPhysicsInfo_RequestBody() {
        }
        
        public GetPhysicsInfo_RequestBody(string Inspection_NO) {
            this.Inspection_NO = Inspection_NO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhysicsInfo_Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhysicsInfo_Response", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.GetPhysicsInfo_ResponseBody Body;
        
        public GetPhysicsInfo_Response() {
        }
        
        public GetPhysicsInfo_Response(phians_laboratory.get_interface.GetPhysicsInfo_ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhysicsInfo_ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPhysicsInfo_Result;
        
        public GetPhysicsInfo_ResponseBody() {
        }
        
        public GetPhysicsInfo_ResponseBody(string GetPhysicsInfo_Result) {
            this.GetPhysicsInfo_Result = GetPhysicsInfo_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="test", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.testRequestBody Body;
        
        public testRequest() {
        }
        
        public testRequest(phians_laboratory.get_interface.testRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class testRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dd;
        
        public testRequestBody() {
        }
        
        public testRequestBody(string dd) {
            this.dd = dd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.testResponseBody Body;
        
        public testResponse() {
        }
        
        public testResponse(phians_laboratory.get_interface.testResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class testResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testResult;
        
        public testResponseBody() {
        }
        
        public testResponseBody(string testResult) {
            this.testResult = testResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testParameters", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.testParametersRequestBody Body;
        
        public testParametersRequest() {
        }
        
        public testParametersRequest(phians_laboratory.get_interface.testParametersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class testParametersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fmName;
        
        public testParametersRequestBody() {
        }
        
        public testParametersRequestBody(string fmName) {
            this.fmName = fmName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testParametersResponse", Namespace="http://tempuri.org/", Order=0)]
        public phians_laboratory.get_interface.testParametersResponseBody Body;
        
        public testParametersResponse() {
        }
        
        public testParametersResponse(phians_laboratory.get_interface.testParametersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class testParametersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testParametersResult;
        
        public testParametersResponseBody() {
        }
        
        public testParametersResponseBody(string testParametersResult) {
            this.testParametersResult = testParametersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface phians_webservice_N1SoapChannel : phians_laboratory.get_interface.phians_webservice_N1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class phians_webservice_N1SoapClient : System.ServiceModel.ClientBase<phians_laboratory.get_interface.phians_webservice_N1Soap>, phians_laboratory.get_interface.phians_webservice_N1Soap {
        
        public phians_webservice_N1SoapClient() {
        }
        
        public phians_webservice_N1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public phians_webservice_N1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public phians_webservice_N1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public phians_webservice_N1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.get_interface.get_infoResponse phians_laboratory.get_interface.phians_webservice_N1Soap.get_info(phians_laboratory.get_interface.get_infoRequest request) {
            return base.Channel.get_info(request);
        }
        
        public string get_info(string clientele) {
            phians_laboratory.get_interface.get_infoRequest inValue = new phians_laboratory.get_interface.get_infoRequest();
            inValue.Body = new phians_laboratory.get_interface.get_infoRequestBody();
            inValue.Body.clientele = clientele;
            phians_laboratory.get_interface.get_infoResponse retVal = ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).get_info(inValue);
            return retVal.Body.get_infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.get_infoResponse> phians_laboratory.get_interface.phians_webservice_N1Soap.get_infoAsync(phians_laboratory.get_interface.get_infoRequest request) {
            return base.Channel.get_infoAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.get_interface.get_infoResponse> get_infoAsync(string clientele) {
            phians_laboratory.get_interface.get_infoRequest inValue = new phians_laboratory.get_interface.get_infoRequest();
            inValue.Body = new phians_laboratory.get_interface.get_infoRequestBody();
            inValue.Body.clientele = clientele;
            return ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).get_infoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.get_interface.GetOrderNUMResponse phians_laboratory.get_interface.phians_webservice_N1Soap.GetOrderNUM(phians_laboratory.get_interface.GetOrderNUMRequest request) {
            return base.Channel.GetOrderNUM(request);
        }
        
        public string GetOrderNUM(string JobNum) {
            phians_laboratory.get_interface.GetOrderNUMRequest inValue = new phians_laboratory.get_interface.GetOrderNUMRequest();
            inValue.Body = new phians_laboratory.get_interface.GetOrderNUMRequestBody();
            inValue.Body.JobNum = JobNum;
            phians_laboratory.get_interface.GetOrderNUMResponse retVal = ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).GetOrderNUM(inValue);
            return retVal.Body.GetOrderNUMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.GetOrderNUMResponse> phians_laboratory.get_interface.phians_webservice_N1Soap.GetOrderNUMAsync(phians_laboratory.get_interface.GetOrderNUMRequest request) {
            return base.Channel.GetOrderNUMAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.get_interface.GetOrderNUMResponse> GetOrderNUMAsync(string JobNum) {
            phians_laboratory.get_interface.GetOrderNUMRequest inValue = new phians_laboratory.get_interface.GetOrderNUMRequest();
            inValue.Body = new phians_laboratory.get_interface.GetOrderNUMRequestBody();
            inValue.Body.JobNum = JobNum;
            return ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).GetOrderNUMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.get_interface.GetmethodResponse phians_laboratory.get_interface.phians_webservice_N1Soap.Getmethod(phians_laboratory.get_interface.GetmethodRequest request) {
            return base.Channel.Getmethod(request);
        }
        
        public string Getmethod(string LZKH, string VORNR) {
            phians_laboratory.get_interface.GetmethodRequest inValue = new phians_laboratory.get_interface.GetmethodRequest();
            inValue.Body = new phians_laboratory.get_interface.GetmethodRequestBody();
            inValue.Body.LZKH = LZKH;
            inValue.Body.VORNR = VORNR;
            phians_laboratory.get_interface.GetmethodResponse retVal = ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).Getmethod(inValue);
            return retVal.Body.GetmethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.GetmethodResponse> phians_laboratory.get_interface.phians_webservice_N1Soap.GetmethodAsync(phians_laboratory.get_interface.GetmethodRequest request) {
            return base.Channel.GetmethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.get_interface.GetmethodResponse> GetmethodAsync(string LZKH, string VORNR) {
            phians_laboratory.get_interface.GetmethodRequest inValue = new phians_laboratory.get_interface.GetmethodRequest();
            inValue.Body = new phians_laboratory.get_interface.GetmethodRequestBody();
            inValue.Body.LZKH = LZKH;
            inValue.Body.VORNR = VORNR;
            return ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).GetmethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.get_interface.GetPhysicsInfo_Response phians_laboratory.get_interface.phians_webservice_N1Soap.GetPhysicsInfo_(phians_laboratory.get_interface.GetPhysicsInfo_Request request) {
            return base.Channel.GetPhysicsInfo_(request);
        }
        
        public string GetPhysicsInfo_(string Inspection_NO) {
            phians_laboratory.get_interface.GetPhysicsInfo_Request inValue = new phians_laboratory.get_interface.GetPhysicsInfo_Request();
            inValue.Body = new phians_laboratory.get_interface.GetPhysicsInfo_RequestBody();
            inValue.Body.Inspection_NO = Inspection_NO;
            phians_laboratory.get_interface.GetPhysicsInfo_Response retVal = ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).GetPhysicsInfo_(inValue);
            return retVal.Body.GetPhysicsInfo_Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.GetPhysicsInfo_Response> phians_laboratory.get_interface.phians_webservice_N1Soap.GetPhysicsInfo_Async(phians_laboratory.get_interface.GetPhysicsInfo_Request request) {
            return base.Channel.GetPhysicsInfo_Async(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.get_interface.GetPhysicsInfo_Response> GetPhysicsInfo_Async(string Inspection_NO) {
            phians_laboratory.get_interface.GetPhysicsInfo_Request inValue = new phians_laboratory.get_interface.GetPhysicsInfo_Request();
            inValue.Body = new phians_laboratory.get_interface.GetPhysicsInfo_RequestBody();
            inValue.Body.Inspection_NO = Inspection_NO;
            return ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).GetPhysicsInfo_Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.get_interface.testResponse phians_laboratory.get_interface.phians_webservice_N1Soap.test(phians_laboratory.get_interface.testRequest request) {
            return base.Channel.test(request);
        }
        
        public string test(string dd) {
            phians_laboratory.get_interface.testRequest inValue = new phians_laboratory.get_interface.testRequest();
            inValue.Body = new phians_laboratory.get_interface.testRequestBody();
            inValue.Body.dd = dd;
            phians_laboratory.get_interface.testResponse retVal = ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).test(inValue);
            return retVal.Body.testResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.testResponse> phians_laboratory.get_interface.phians_webservice_N1Soap.testAsync(phians_laboratory.get_interface.testRequest request) {
            return base.Channel.testAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.get_interface.testResponse> testAsync(string dd) {
            phians_laboratory.get_interface.testRequest inValue = new phians_laboratory.get_interface.testRequest();
            inValue.Body = new phians_laboratory.get_interface.testRequestBody();
            inValue.Body.dd = dd;
            return ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).testAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phians_laboratory.get_interface.testParametersResponse phians_laboratory.get_interface.phians_webservice_N1Soap.testParameters(phians_laboratory.get_interface.testParametersRequest request) {
            return base.Channel.testParameters(request);
        }
        
        public string testParameters(string fmName) {
            phians_laboratory.get_interface.testParametersRequest inValue = new phians_laboratory.get_interface.testParametersRequest();
            inValue.Body = new phians_laboratory.get_interface.testParametersRequestBody();
            inValue.Body.fmName = fmName;
            phians_laboratory.get_interface.testParametersResponse retVal = ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).testParameters(inValue);
            return retVal.Body.testParametersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<phians_laboratory.get_interface.testParametersResponse> phians_laboratory.get_interface.phians_webservice_N1Soap.testParametersAsync(phians_laboratory.get_interface.testParametersRequest request) {
            return base.Channel.testParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<phians_laboratory.get_interface.testParametersResponse> testParametersAsync(string fmName) {
            phians_laboratory.get_interface.testParametersRequest inValue = new phians_laboratory.get_interface.testParametersRequest();
            inValue.Body = new phians_laboratory.get_interface.testParametersRequestBody();
            inValue.Body.fmName = fmName;
            return ((phians_laboratory.get_interface.phians_webservice_N1Soap)(this)).testParametersAsync(inValue);
        }
    }
}
